name: objectivist
description: Reader and writer for Wavefront .obj files in Dart.
version: 0.0.1
author: R.S. Schermer <roland0507@gmail.com>
homepage: https://github.com/rsschermer/objectivist.dart

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  resource: '>=2.0.2 <2.1.0'
  rl_matrix: '>=0.6.2 <0.7.0'

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
